### ISSUE TITLE
Add `screenshots` to your `pub.dev`

### ISSUE THREAD

**Issue by FMorschel** [diegoveloper/flutter_percent_indicator#192]
Hi! Just a suggestion! You have some screenshots in your readme file, you can now add them to the `pubspec.yaml` and they will show on your pub.dev side screen and search screen.

Take a look at this package and don't forget to search for it as well to see how it shows in the search page.
https://pub.dev/packages/fl_chart

E.g.:

```yaml
screenshots:
  - description: 'LineChartSample1 and LineChartSample2'
    path: pub_screenshots/line_chart.jpg
  - description: 'LineChartSample10'
    path: pub_screenshots/line_chart_sample_10.gif
  - description: 'BarChartSample1 and BarChartSample2'
    path: pub_screenshots/bar_chart.jpg
  - description: 'BarChartSample7'
    path: pub_screenshots/bar_chart_sample_7.gif
  - description: 'PieChartSample1, PieChartSample2 and PieChartSample3'
    path: pub_screenshots/pie_chart.jpg
  - description: 'ScatterChartSample2'
    path: pub_screenshots/scatter_chart_sample_2.gif
  - description: 'RadarChartSample1'
    path: pub_screenshots/radar_chart_sample_1.jpg
```
